package locators

class AndroidLocator {

	static final String ONBOARDING_TITLE = "//android.widget.TextView[@text='Selamat datang di Vello']"
	static final String ONBOARDING_SUB_TITLE = "//android.widget.TextView[@text='Nikmati kemudahan bertransaksi dengan aman dan cepat.']"
	static final String ONBOARDING_BTN_MULAI = "Mulai"
	static final String BTN_DAFTAR = "Daftar"
	static final String BTN_MASUK = "Masuk"
	static final String LOGIN_TF_USER_NAME = "//android.widget.ScrollView/android.widget.EditText[1]"
	static final String LOGIN_TF_PASSWORD = "//android.widget.ScrollView/android.widget.EditText[2]"
	static final String LOGIN_BTN_MASUK = "Masuk"
	static final String HOME_TAB_BERANDA = "new UiSelector().text('Beranda')"
	static final String HOME_TAB_AKTIFITAS = "new UiSelector().text('Aktivitas').instance(1)"
	static final String HOME_PROFILE_ICON = "//android.widget.ScrollView/android.view.View/android.view.View/android.view.View/android.view.View[1]"
	static final String PROFILE_TITLE = "//android.widget.TextView[@text='Profil']"
	static final String PROFILE_COPYPASTE_ICON = "//android.view.View[@content-desc='Salin']"
	static final String PROFILE_TITLE_LANGUAGE = "//android.widget.TextView[@text='Pilih Bahasa']"
	static final String LANGUAGE_TOGLE_ID = "//android.widget.TextView[@text='ID']"
	static final String LANGUAGE_TOGLE_EN = "//android.widget.TextView[@text='EN']"
	static final String PROFILE_SECTION_EMAIL = "//android.widget.TextView[@text='Alamat Email']"
	static final String PROFILE_ICON_ARROW_EMAIL = "//android.view.View[@content-desc='Aksi']"
	static final String EDIT_EMAIL_TITLE_SCREEN = "//android.widget.TextView[@text='Edit Email']"
	static final String EDIT_EMAIL_TXTFIELD_CURRENT = "//android.widget.TextView[@text='Masukkan email terdaftar'']"
	static final String EDIT_EMAIL_TXTFIELD_NEW = "//android.widget.TextView[@text='Masukkan email baru']"
	static final String EDIT_EMAIL_NEXT_BTN = "//android.view.View[@content-desc='Lanjut']"
	static final String OTP_TITLE_SCREEN = ""
	static final String OTP_BOX_1 = ""
	static final String OTP_BOX_2 = ""
	static final String OTP_BOX_3 = ""
	static final String OTP_BOX_4 = ""
	static final String OTP_BOX_5 = ""
	static final String OTP_BOX_6 = ""
	static final String INPUT_PIN_TITLE_SCREEN = ""
	static final String SUCCESS_ALERT_TITLE = ""
	static final String SUCCESS_ALERT_BTN = ""
	static final String ACCOUNT_LIST_TAB_TITLE_TABUNGAN = ""
	static final String ACCOUNT_LIST_TAB_TITLE_EWALLET = ""
	static final String ACCOUNT_LIST_TAB_TITLE_DEPOSITO = ""
	static final String ACCOUNT_LIST_TAB_TITLE_TABUNGAN_RENCANA = ""
	static final String ACCOUNT_LIST_TAB_TITLE_PINJAMAN = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_TABUNGAN = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_EWALLET = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_DEPOSITO = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_TABUNGAN_RENCANA = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_PINJAMAN = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_TABUNGAN = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_SALDO_EWALLET = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_SALDO_DEPOSITO = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_SALDO_TABUNGAN_RENCANA = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_SALDO_PINJAMAN = ""
	static final String ACCOUNT_LIST_CARD_LIST_INDEX_0 = ""
	static final String ACCOUNT_LIST_ACCOUNT_NAME_TEXT = ""
	static final String CARD_DETAIL_SEE_DETAIL_BTN = ""
	static final String ACCOUNT_EDIT_ACCOUNT_BTN = ""
	static final String CHANGE_ACCOUNT_TITLE_SCREEN = ""
	static final String CHANGE_ACCOUNT_RADIO_BTN_INDEX_0 = ""
	static final String CHANGE_ACCOUNT_RADIO_BTN_INDEX_1 = ""
	static final String CHANGE_ACCOUNT_NEXT_BTN = ""
	static final String TOAST_MESSAGE_CHANGE_ACCOUNT_SUCCESS = ""





	static final String TITLE_HOME_SCREEN = ""
	static final String TITLE_BTN_NEXT_ATAS = "//XCUIElementTypeOther[@name='Ďalej']"
}