package locators

class AndroidLocator {

	static final String ONBOARDING_TITLE = "//android.widget.TextView[@text='Selamat datang di Vello']"
	static final String ONBOARDING_SUB_TITLE = "//android.widget.TextView[@text='Nikmati kemudahan bertransaksi dengan aman dan cepat.']"
	static final String ONBOARDING_BTN_MULAI = "Mulai"
	static final String BTN_DAFTAR = "Daftar"
	static final String BTN_MASUK = "Masuk"
	static final String LOGIN_TF_USER_NAME = "//android.widget.ScrollView/android.widget.EditText[1]"
	static final String LOGIN_TF_PASSWORD = "//android.widget.ScrollView/android.widget.EditText[2]"
	static final String LOGIN_BTN_MASUK = "Masuk"
	static final String HOME_TOOLBAR_BERANDA = "Beranda"
	static final String HOME_PROFILE_ICON = "//android.widget.ScrollView/android.view.View/android.view.View/android.view.View/android.view.View[1]"
	static final String PROFILE_TITLE = "//android.widget.TextView[@text='Profil']"
	static final String PROFILE_COPYPASTE_ICON = "//android.view.View[@content-desc='Salin']"
	static final String PROFILE_TITLE_LANGUAGE = ""
	static final String LANGUAGE_TOGLE_ID = ""
	static final String LANGUAGE_TOGLE_EN = ""
	static final String PROFILE_SECTION_EMAIL = ""
	static final String PROFILE_ICON_ARROW_EMAIL = ""
	static final String EDIT_EMAIL_TITLE_SCREEN = ""
	static final String EDIT_EMAIL_TXTFIELD_CURRENT = ""
	static final String EDIT_EMAIL_TXTFIELD_NEW = ""
	static final String EDIT_EMAIL_NEXT_BTN = ""
	static final String OTP_TITLE_SCREEN = ""
	static final String OTP_BOX_1 = ""
	static final String OTP_BOX_2 = ""
	static final String OTP_BOX_3 = ""
	static final String OTP_BOX_4 = ""
	static final String OTP_BOX_5 = ""
	static final String OTP_BOX_6 = ""
	static final String INPUT_PIN_TITLE_SCREEN = ""
	static final String SUCCESS_ALERT_TITLE = ""
	static final String SUCCESS_ALERT_BTN = ""
}
