package locators

import localization.Localize

class IOSLocator {

	static final String ONBOARDING_TITLE = "//android.widget.TextView[@text='Selamat datang di Vello']"
	static final String ONBOARDING_SUB_TITLE = "//android.widget.TextView[@text='Nikmati kemudahan bertransaksi dengan aman dan cepat.']"
	static final String ONBOARDING_BTN_MULAI = "//android.widget.TextView[@text='Mulai']"
	static final String BTN_DAFTAR = "//android.view.View[@content-desc='Daftar']"
	static final String BTN_MASUK = "//android.view.View[@content-desc='Masuk']"
	static final String LOGIN_TF_USER_NAME = "//android.widget.TextView[@text='Masukkan Nama Pengguna']"
	static final String LOGIN_TF_PASSWORD = "//android.widget.TextView[@text='Masukkan Kata Sandi']"
	static final String LOGIN_BTN_MASUK = "//android.view.View[@content-desc='Masuk']"
	static final String HOME_TAB_BERANDA = "new UiSelector().text('Beranda')"
	static final String HOME_TAB_AKTIFITAS = "new UiSelector().text('Aktivitas').instance(1)"
	static final String HOME_PROFILE_ICON = "//android.widget.ScrollView/android.view.View/android.view.View/android.view.View/android.view.View[1]"
	static final String PROFILE_TITLE = "//android.widget.TextView[@text='Profil']"
	static final String PROFILE_COPYPASTE_ICON = "//android.view.View[@content-desc='Salin']"
	static final String PROFILE_TITLE_LANGUAGE = ""
	static final String LANGUAGE_TOGLE_ID = ""
	static final String LANGUAGE_TOGLE_EN = ""
	static final String PROFILE_SECTION_EMAIL = ""
	static final String PROFILE_ICON_ARROW_EMAIL = ""
	static final String EDIT_EMAIL_TITLE = ""
	static final String EDIT_EMAIL_TXTFIELD_CURRENT = ""
	static final String EDIT_EMAIL_TXTFIELD_NEW = ""
	static final String EDIT_EMAIL_NEXT_BTN = ""
	static final String OTP_TITLE_SCREEN = ""
	static final String OTP_BOX_1 = ""
	static final String OTP_BOX_2 = ""
	static final String OTP_BOX_3 = ""
	static final String OTP_BOX_4 = ""
	static final String OTP_BOX_5 = ""
	static final String OTP_BOX_6 = ""
	static final String INPUT_PIN_TITLE_SCREEN = ""
	static final String SUCCESS_ALERT_TITLE = ""
	static final String SUCCESS_ALERT_BTN = ""
	static final String ACCOUNT_LIST_TAB_TITLE_TABUNGAN = ""
	static final String ACCOUNT_LIST_TAB_TITLE_EWALLET = ""
	static final String ACCOUNT_LIST_TAB_TITLE_DEPOSITO = ""
	static final String ACCOUNT_LIST_TAB_TITLE_TABUNGAN_RENCANA = ""
	static final String ACCOUNT_LIST_TAB_TITLE_PINJAMAN = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_TABUNGAN = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_EWALLET = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_DEPOSITO = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_TABUNGAN_RENCANA = ""
	static final String ACCOUNT_LIST_LABEL_SALDO_PINJAMAN = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_TABUNGAN = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_SALDO_EWALLET = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_SALDO_DEPOSITO = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_SALDO_TABUNGAN_RENCANA = ""
	static final String ACCOUNT_LIST_ICN_SHOWHIDE_SALDO_PINJAMAN = ""
	static final String ACCOUNT_LIST_CARD_LIST_INDEX_0 = ""
	static final String ACCOUNT_LIST_ACCOUNT_NAME_TEXT = ""
	static final String CARD_DETAIL_SEE_DETAIL_BTN = ""
	static final String ACCOUNT_EDIT_ACCOUNT_BTN = ""
	static final String CHANGE_ACCOUNT_TITLE_SCREEN = ""
	static final String CHANGE_ACCOUNT_RADIO_BTN_INDEX_0 = ""
	static final String CHANGE_ACCOUNT_RADIO_BTN_INDEX_1 = ""
	static final String CHANGE_ACCOUNT_NEXT_BTN = ""
	static final String TOAST_MESSAGE_CHANGE_ACCOUNT_SUCCESS = ""




	static final String TITLE_HOME_SCREEN = "//XCUIElementTypeStaticText[@name='${Localize.get('TITLE_HOME_SCREEN')}']"
	static final String TITLE_BTN_NEXT_ATAS = "//XCUIElementTypeButton[@name='${Localize.get('TITLE_BTN_NEXT_ATAS')}']"
	static final String LIST_ITEM_CODING_JURNAL = "//XCUIElementTypeStaticText[@name='${Localize.get('LIST_ITEM_CODING_JURNAL')}']"
	static final String LIST_ITEM_HACKER_NEWS = "//XCUIElementTypeStaticText[@name='${Localize.get('LIST_ITEM_HACKER_NEWS')}']"
}